services:
  fishjam:
    image: "ghcr.io/fishjam-dev/fishjam:${TAG:-edge}"
    container_name: fishjam
    restart: on-failure
    healthcheck:
      test: >
        curl --fail -H "authorization: Bearer development" http://localhost:5002/room || exit 1
      interval: 3s
      retries: 2
      timeout: 2s
      start_period: 30s
    environment:
      FJ_HOST: "localhost:5002"
      FJ_PORT: 5002
      FJ_SERVER_API_TOKEN: "development"
      FJ_COMPONENTS_USED: "file hls rtsp sip recording"
      FJ_WEBRTC_TURN_IP: "${INTEGRATED_TURN_IP:-127.0.0.1}"
      FJ_WEBRTC_TURN_LISTEN_IP: "0.0.0.0"
      FJ_WEBRTC_TURN_PORT_RANGE: "50000-50050"
      FJ_WEBRTC_TURN_TCP_PORT: "49999"
      FJ_SIP_IP: "127.0.0.1"
    ports:
      - "5002:5002"
      - "49999:49999"
      - "50000-50050:50000-50050/udp"
