version: "3"

services:
  test:
    image: membraneframeworklabs/docker_membrane:v2.2.0
    command: sh -c "cd app/ && mix deps.get && mix coveralls.json --warnings-as-errors"
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    ports:
      - "4000:4000"
    depends_on:
      jellyfish:
        condition: service_healthy

  jellyfish:
    extends:
      file: docker-compose-dev.yaml
      service: jellyfish
    environment:
      - JF_HOST=jellyfish:5002
    volumes:
      - ./test/fixtures:/app/jellyfish_resources/file_component_sources
