version: "3"

services:
  test:
    image: hexpm/elixir:1.14.4-erlang-25.3.2-alpine-3.16.5
    command: sh -c "cd app/ && apk add git && mix local.hex --force && mix local.rebar --force && mix deps.get && mix coveralls.json --warnings-as-errors"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      jellyfish:
        condition: service_healthy

  jellyfish:
    extends:
      file: docker-compose-dev.yaml
      service: jellyfish
    environment:
      - JF_HOST=jellyfish:5002
