version: "3"

services:
  jellyfish:
    image: "ghcr.io/jellyfish-dev/jellyfish:${TAG:-latest}"
    container_name: jellyfish
    restart: on-failure
    # network_mode: "host"
    healthcheck:
      test: >
        curl --fail -H "authorization: Bearer development" http://localhost:5002/room || exit 1
      interval: 15s
      retries: 5
      timeout: 10s
    environment:
      VIRTUAL_HOST: "localhost"
      USE_INTEGRATED_TURN: "true"
      INTEGRATED_TURN_IP: "${INTEGRATED_TURN_IP:-127.0.0.1}"
      INTEGRATED_TURN_PORT_RANGE: "50000-65355"
      INTEGRATED_TCP_TURN_PORT: "49999"
      SERVER_API_TOKEN: "development"
      PORT: 5002
      SECRET_KEY_BASE: "super-secret-key"
    ports:
      - "5002:5002"
